version: 0.2

phases:
  build:
    commands:
      - echo "Listing files before uploading artifacts:"
      - ls -la
      # Remove the zip command here
artifacts:
  files:
    - appspec.yml
    - index.html
    - style.css
    - images/**/*
