version: 0.2

phases:
  build:
    commands:
      - echo "Listing files before zipping:"
      - ls -la
      - echo "Packaging static site for CodeDeploy"
      - zip -r build-output.zip .     # Zip all files in current directory
      - ls -l build-output.zip  

artifacts:
  files:
    - build-output.zip
